language: python

python:
  - 2.7
  - 3.8

env:
  - COQ_VERSION="master"   COQ_PACKAGE="coq"                            PPA="ppa:jgross-h/coq-master-daily"              PYTHON="python"
  - COQ_VERSION="v8.11"    COQ_PACKAGE="coq"                            PPA="ppa:jgross-h/coq-8.11-daily"                PYTHON="python"
  - COQ_VERSION="v8.10"    COQ_PACKAGE="coq"                            PPA="ppa:jgross-h/coq-8.10-daily"                PYTHON="python"
  - COQ_VERSION="v8.9"     COQ_PACKAGE="coq"                            PPA="ppa:jgross-h/coq-8.9-daily"                 PYTHON="python"
  - COQ_VERSION="v8.8"     COQ_PACKAGE="coq"                            PPA="ppa:jgross-h/coq-8.8-daily"                 PYTHON="python"
  - COQ_VERSION="v8.7"     COQ_PACKAGE="coq"                            PPA="ppa:jgross-h/coq-8.7-daily"                 PYTHON="python"
  - COQ_VERSION="v8.6"     COQ_PACKAGE="coq"                            PPA="ppa:jgross-h/coq-8.6-daily"                 PYTHON="python"
  - COQ_VERSION="v8.5"     COQ_PACKAGE="coq"                            PPA="ppa:jgross-h/coq-8.5-daily"                 PYTHON="python"
  - COQ_VERSION="8.11.1"   COQ_PACKAGE="coq-8.11.1"                     PPA="ppa:jgross-h/many-coq-versions-ocaml-4-05"  PYTHON="python"
  - COQ_VERSION="8.10.2"   COQ_PACKAGE="coq-8.10.2"                     PPA="ppa:jgross-h/many-coq-versions-ocaml-4-05"  PYTHON="python"
  - COQ_VERSION="8.9.1"    COQ_PACKAGE="coq-8.9.1"                      PPA="ppa:jgross-h/many-coq-versions"             PYTHON="python"
  - COQ_VERSION="8.8.2"    COQ_PACKAGE="coq-8.8.2"                      PPA="ppa:jgross-h/many-coq-versions"             PYTHON="python"
  - COQ_VERSION="8.7.2"    COQ_PACKAGE="coq-8.7.2"                      PPA="ppa:jgross-h/many-coq-versions"             PYTHON="python"
  - COQ_VERSION="8.6.1"    COQ_PACKAGE="coq-8.6.1"                      PPA="ppa:jgross-h/many-coq-versions"             PYTHON="python"
  - COQ_VERSION="8.5pl3"   COQ_PACKAGE="coq-8.5pl3 libcoq-8.5pl3-ocaml" PPA="ppa:jgross-h/many-coq-versions"             PYTHON="python"

before_install:
  - if [ ! -z "$PPA" ]; then sudo add-apt-repository "$PPA" -y; fi
  - travis_retry ./etc/sudo-apt-get-update.sh -q
  - travis_retry sudo apt-get install $COQ_PACKAGE -y

script: make has-all-tests && make check CAT_ALL_LOGS=1
